project_id = "fwybnoctkktseemhacrw"

[functions.process-exit-request]
verify_jwt = false

[functions.generate-recurring]
verify_jwt = false

[functions.fire-webhook]
verify_jwt = false

[functions.test-integration]
verify_jwt = false

[functions.sync-ads-data]
verify_jwt = false

[functions.clear-logs]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.export-integracoes]
verify_jwt = false

[functions.evolution-ai-chat]
verify_jwt = false